<?php
if (!function_exists('wp_handle_upload')) {
  require_once(ABSPATH . 'wp-admin/includes/image.php');
  require_once(ABSPATH . 'wp-admin/includes/file.php');
  require_once(ABSPATH . 'wp-admin/includes/media.php');
}
?>

<?php get_header(); ?>
<?php // $current_user = get_current_user_id(); 
?>
<?php // echo $current_user; 
?>
<?php
$args = array(
  'author'        =>  $current_user->ID,
  'orderby' => 'post_date',
  'order'         =>  'ASC',
  'posts_per_page' => 1,
  'post_type' => 'doctor'
);
$doctor = get_posts($args)[0];
if ($_FILES['avatar']) {
  $photo = media_handle_upload('avatar', $doctor->ID);
}
?>
<?php
if ($_POST['first_name'] || $_POST['last_name'] || $_POST['user_email']) {
  wp_update_user(array(
    'ID' => $current_user->ID,
    'first_name' => $_POST['first_name'],
    'last_name' => $_POST['last_name'],
    'user_email' => $_POST['user_email']
  ));
}
$updated_user = get_user_by('ID', $current_user->ID);
unset($_POST['first_name']);
unset($_POST['last_name']);
unset($_POST['email']);
unset($_POST['user_number']);
unset($_POST['user_email']);
foreach ($_POST as $key => $value) :
  update_field($key, $value, $doctor->ID);
endforeach;
?>

<?php


// $uploadedfile = $_FILES['avatar'];

// /* You can use wp_check_filetype() function to check the
// file type and go on wit the upload or stop it.*/

// $movefile = wp_handle_upload( $uploadedfile, array( 'test_form' => false ));

// if ( $movefile && !isset( $movefile['error'] ) ) {
// echo "File is valid, and was successfully uploaded.\n";
// var_dump( $movefile);
// // echo $movefile['url'];
// } else {
// /**
// * Error generated by _wp_handle_upload()
// * @see _wp_handle_upload() in wp-admin/includes/file.php
// */
// echo 'error';
// echo $movefile['error'];
// }
?>

<main role="main" aria-label="Content" class="bg-back-grey pt-8">
  <!-- section -->
  <section>

    <?php if (have_posts()) : while (have_posts()) : the_post(); ?>

        <!-- article -->
        <article id="post-<?php the_ID(); ?>" <?php post_class(); ?>>
          <div class="doctor-registration bg-white my-12 max-w-6xl mx-auto py-12">
            <h2 class="text-pink text-center mb-16">Update Profile</h2>
            <form enctype="multipart/form-data" action="/update-profile" method="POST">
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Email</label>
                  <input type="email" name="user_email" value="<?php echo $updated_user->user_email; ?>" />
                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">ClearCorrect User Number</label>
                  <input type="text" name="user_number" value="<?php echo $current_user->ID; ?>" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">First Name</label>
                  <input type="text" name="first_name" value="<?php echo $current_user->first_name; ?>" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Last Name</label>
                  <input type="text" name="last_name" value="<?php echo $current_user->last_name; ?>" />

                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Degree</label>
                  <div class="select">
                    <select name="degree">
                      <option <?php if (get_field('degree', $doctor->ID) == 'Make Selection') echo 'selected'; ?> value="Make Selection">Make Selection</option>
                      <option <?php if (get_field('degree', $doctor->ID) == 'One') echo 'selected'; ?>value="One">One</option>
                      <option <?php if (get_field('degree', $doctor->ID) == 'Two') echo 'selected '; ?>value="Two">Two</option>
                    </select>
                  </div>
                </div>
                <div class="wp-block-column flex flex-col">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Specialty</label>
                  <div class="select">

                    <select name="specialty">
                      <option <?php if (get_field('specialty', $doctor->ID) == 'Make Selection') echo 'selected '; ?> value="Make Selection">Make Selection</option>
                      <option <?php if (get_field('specialty', $doctor->ID) == 'One') echo 'selected '; ?>value="One">One</option>
                      <option <?php if (get_field('specialty', $doctor->ID) == 'Two') echo 'selected  '; ?>value="Two">Two</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="flex items-center max-w-4xl mx-auto avatar">
                <?php
                $photo = get_the_post_thumbnail_url($doctor->ID);
                if (empty($photo)) $photo = 'http://ec2-18-144-32-142.us-west-1.compute.amazonaws.com/wp-content/uploads/2021/01/avatar.png';
                ?>
                <img src="<?php echo $photo; ?>" />
                <div class="flex flex-col">
                  <input type="file" id="avatar" name="avatar" accept="image/png, image/jpeg">
                  <label class="text-h5-grey uppercase text-xs font-bold">Profile Image (Optional)</label>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Practice Country</label>
                  <div class="select">
                    <select name="practice-country">
                      <option <?php if (get_field('practice-country', $doctor->ID) == 'Make Selection') echo 'selected '; ?> value="Make Selection">Make Selection</option>
                      <option <?php if (get_field('practice-country', $doctor->ID) == 'One') echo 'selected '; ?>value="One">One</option>
                      <option <?php if (get_field('practice-country', $doctor->ID) == 'Two') echo 'selected '; ?>value="Two">Two</option>
                    </select>
                  </div>
                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Practice Province/State</label>
                  <div class="select">

                  <select name="practice-state">
                      <option <?php if (get_field('practice-state', $doctor->ID) == 'Make Selection') echo 'selected '; ?> value="Make Selection">Make Selection</option>
                      <option <?php if (get_field('practice-state', $doctor->ID) == 'One') echo 'selected '; ?>value="One">One</option>
                      <option <?php if (get_field('practice-state', $doctor->ID) == 'Two') echo 'selected '; ?>value="Two">Two</option>
                    </select>
                  </div>
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Address (Optional)</label>
                  <input type="text" name="address_1" value="<?php the_field('address_1', $doctor->ID); ?>" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Second Address(Optional)</label>
                  <input type="text" name="address_2" value="<?php the_field('address_2', $doctor->ID); ?>" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">City (Optional)</label>
                  <input type="text" name="city" value="<?php the_field('city', $doctor->ID); ?>" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Zip/Postal Code (Optional)</label>
                  <input type="text" name="zip" value="<?php the_field('zip', $doctor->ID); ?>" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Practice Email (Optional)</label>
                  <input type="email" name="practice_email" value="<?php the_field('practice_email', $doctor->ID); ?>" />

                </div>
                <div class="wp-block-column flex flex-col"">
                  <label class=" text-h5-grey uppercase text-xs font-bold">Phone (optional)</label>
                  <input type="text" name="phone" value="<?php the_field('phone', $doctor->ID); ?>" />
                </div>
              </div>
              <div class="wp-block-columns max-w-4xl mx-auto">
                <div class="wp-block-column flex flex-col">
                  <label class="text-h5-grey uppercase text-xs font-bold">Website (Optional)</label>
                  <input type="text" name="website" value="<?php the_field('website', $doctor->ID); ?>" />

                </div>
                <div class="wp-block-column flex flex-col">
                </div>
              </div>






          </div>


          </div>
          </div>
          <div class=" max-w-4xl w-full mx-auto flex flex-col">

            <input type="submit" class="w-full max-w-xs bg-pink text-white text-sm uppercase mx-auto rounded my-12 py-4 font-bold" value="SUBMIT" />
          </div>

          </form>
          </div>


          <?php edit_post_link(); ?>

        </article>
        <!-- /article -->

      <?php endwhile; ?>

    <?php else : ?>

      <!-- article -->
      <article>

        <h2><?php _e('Sorry, nothing to display.', 'html5blank'); ?></h2>

      </article>
      <!-- /article -->

    <?php endif; ?>

  </section>
  <!-- /section -->
</main>
<?php get_footer(); ?>